### PR TITLE
Make oM properties virtual

### LINKED ISSUE #43: Add virtual keyword to oM properties
In line with the discussion on https://github.com/BHoM/BHoM/issues/733 and subsequent changes to BHoM in https://github.com/BHoM/BHoM/issues/734 it is desirable for all objects to now contain the `virtual` modifier to provide greater flexibility for developers and users wishing to create BHoM objects in their workflows.

This issue is to instruct @BHoMBot to carry out the task of adding the `virtual` modifier to any object in the oM of this repository where it does not already exist.

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #43

### CODE REVIEW

**Comment by epignatelli** [comment]
> I would recommend the Toolkit lead to do a usual thorough review in case the `virtual` keyword has been added inadvertently to the wrong properties.

@FraserGreenroyd maybe it is better not to approve automatically if the pr requires a closer look. Not this case though!

**Comment by epignatelli** [comment]
Do not merge this please, as I am making sure that also `IObject`s, like `ActionConfig` and `HTTPConfig` are included in the change.

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd maybe it is better not to approve automatically if the pr requires a closer look. Not this case though!

Hi @epignatelli - I approve based on what code has changed and based on the original issue/instruction to BHoMBot as part of the CI process for using BHoMBot to show that this action was supervised and completed as far as I can tell, but onus is always on the toolkit leads to verify from their perspective as well :smile:

**Comment by epignatelli** [comment]
I understand, but it still is one click away from merging, in case of issues.

**Pull request merged**
