### PR TITLE
Updates namespaces to Adapters per compliance

### LINKED ISSUE #53: HTTP_Toolkit: Namespace update from `External` to `Adapters`
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.HTTP` or `BH.Engine.Adapters.HTTP` instead of `BH.oM.HTTP`, etc.

The Adapter namespace should remain at `BH.Adapter.HTTP` instead of `BH.Adapter.External.HTTP`.

#### Suggestions to restore compliance:

As above.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #53 

Updated namespaces per new BHoM compliance requirements.

### CODE REVIEW

**Comment by epignatelli** [comment]
There are no actual changes to functionalities here - @alelom this seems something for you more than me?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Versioning is not correct for the current milestone, and each versioning only needs to handle the changes made to that toolkit. See comments on CarbonQueryDatabase_Toolkit for more info.

**Review by alelom — COMMENTED** [review]
Code looks good to me. Please address @FraserGreenroyd comment before I can approve.

**Review by FraserGreenroyd — APPROVED** [review]

**Pull request merged**
