### PR TITLE
Add CI files

### LINKED ISSUE #26: Include CI checks
#### Broken rules:

The repo does not have compliance check. Namely: `CheckCore`, `CheckInstaller`, and `CheckCompliance`.

#### Suggestions to restore compliance:

Add the CI checks

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #26

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
All checks have passed, this is ready for review and merge :smile:

**Comment by epignatelli** [comment]
Thanks guys!

**Pull request merged**
